#!/bin/sh
#
# Wake the network manager after sleep
#

case "$1" in
  resume|thaw)
    service network-manager stop
    rm /var/lib/NetworkManager/NetworkManager.state
    service network-manager start
    ;;
esac
